import type { Edition } from "../data.js";
import board20260824 from "./2026-08-24.json" with { type: "json" };
import board20260821 from "./2026-08-21.json" with { type: "json" };

/** Generated by scripts/publish.mjs. Do not hand-order this list. */
export const AUTOMATED_BOARDS: Edition[] = [
  board20260824 as Edition,
  board20260821 as Edition,
];
