import type { Edition } from "../data.js";
import board20260904 from "./2026-09-04.json" with { type: "json" };
import board20260903 from "./2026-09-03.json" with { type: "json" };
import board20260902 from "./2026-09-02.json" with { type: "json" };
import board20260901 from "./2026-09-01.json" with { type: "json" };
import board20260828 from "./2026-08-28.json" with { type: "json" };
import board20260827 from "./2026-08-27.json" with { type: "json" };
import board20260826 from "./2026-08-26.json" with { type: "json" };
import board20260825 from "./2026-08-25.json" with { type: "json" };
import board20260824 from "./2026-08-24.json" with { type: "json" };
import board20260821 from "./2026-08-21.json" with { type: "json" };

/** Generated by scripts/publish.mjs. Do not hand-order this list. */
export const AUTOMATED_BOARDS: Edition[] = [
  board20260904 as Edition,
  board20260903 as Edition,
  board20260902 as Edition,
  board20260901 as Edition,
  board20260828 as Edition,
  board20260827 as Edition,
  board20260826 as Edition,
  board20260825 as Edition,
  board20260824 as Edition,
  board20260821 as Edition,
];
