import type { MorningPool } from "../pool.js";
import pool0 from "./2026-08-20.json" with { type: "json" };

/** Generated by scripts/pool.mjs for Vite and the Vercel Node function. */
export const MORNING_POOLS = [pool0] as MorningPool[];
