#!/usr/bin/env node
/**
 * Derive small, source-grounded board previews from the first page of each PDF.
 * This intentionally changes no board or packet data. It uses macOS Quick Look
 * locally and pdftoppm on the Linux weekday publisher.
 *
 *   npm run previews -- 2026-08-24
 */

import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const boardDate = String(process.argv[2] || "").slice(0, 10);
if (!/^\d{4}-\d{2}-\d{2}$/.test(boardDate)) {
  console.error("usage: npm run previews -- YYYY-MM-DD [--force]");
  process.exit(1);
}

const force = process.argv.includes("--force");
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const boardPath = join(root, "src", "boards", `${boardDate}.json`);
const legacyPapers = boardDate === "2026-08-20"
  ? [
      "2608.16590", "2608.14929", "2608.18171", "2608.18565", "2608.18973",
      "2608.19070", "2608.18375", "2608.18451", "2608.18417",
    ].map((arxivId) => ({ arxivId }))
  : null;
if (!existsSync(boardPath) && !legacyPapers) {
  console.error(`No generated board at src/boards/${boardDate}.json`);
  process.exit(1);
}

const board = existsSync(boardPath) ? JSON.parse(readFileSync(boardPath, "utf8")) : null;
const papers = board && Array.isArray(board.papers) ? board.papers : legacyPapers || [];
if (!papers.length) {
  console.error(`${boardDate} has no papers.`);
  process.exit(1);
}

const outputDir = join(root, "public", "previews");
const workDir = mkdtempSync(join(tmpdir(), "paperscroll-previews-"));
mkdirSync(outputDir, { recursive: true });

function writePreviewManifest() {
  const ids = readdirSync(outputDir)
    .filter((name) => /^\d{4}\.\d{4,5}\.jpg$/.test(name))
    .map((name) => name.slice(0, -4))
    .sort();
  const lines = ids.map((id) => `  "${id}",`).join("\n");
  writeFileSync(
    join(root, "src", "previewIds.ts"),
    `// Generated by scripts/previews.mjs. Image availability never affects board membership.\nexport const PREVIEW_IDS = [\n${lines}\n] as const;\n`,
  );
}

function renderFirstPage(pdfPath, arxivId) {
  const jpegPath = join(workDir, `${arxivId}.jpg`);

  if (process.platform === "darwin") {
    execFileSync("qlmanage", ["-t", "-s", "720", "-o", workDir, pdfPath], {
      stdio: "ignore",
    });
    const quickLookPath = join(workDir, `${basename(pdfPath)}.png`);
    execFileSync(
      "sips",
      ["-s", "format", "jpeg", "-s", "formatOptions", "76", quickLookPath, "--out", jpegPath],
      { stdio: "ignore" },
    );
    rmSync(quickLookPath, { force: true });
    return jpegPath;
  }

  const outputPrefix = join(workDir, arxivId);
  execFileSync(
    "pdftoppm",
    ["-jpeg", "-f", "1", "-singlefile", "-scale-to", "720", "-jpegopt", "quality=76", pdfPath, outputPrefix],
    { stdio: "ignore" },
  );
  return jpegPath;
}

let failures = 0;
try {
  for (const paper of papers) {
    const arxivId = String(paper.arxivId || "").trim();
    try {
      if (!/^\d{4}\.\d{4,5}$/.test(arxivId)) {
        throw new Error(`invalid arXiv ID: ${arxivId || "missing"}`);
      }
      const destination = join(outputDir, `${arxivId}.jpg`);
      if (!force && existsSync(destination)) {
        console.error(`${arxivId}: preview already exists`);
        continue;
      }

      const response = await fetch(`https://arxiv.org/pdf/${arxivId}`, {
        headers: { "User-Agent": "PaperScroll/1.0 (source-grounded paper preview)" },
        signal: AbortSignal.timeout(45_000),
      });
      if (!response.ok) throw new Error(`arXiv returned ${response.status}`);

      const pdfPath = join(workDir, `${arxivId}.pdf`);
      const bytes = Buffer.from(await response.arrayBuffer());
      if (bytes.subarray(0, 5).toString() !== "%PDF-") {
        throw new Error("arXiv response was not a PDF");
      }
      writeFileSync(pdfPath, bytes);
      const jpegPath = renderFirstPage(pdfPath, arxivId);
      renameSync(jpegPath, destination);
      rmSync(pdfPath, { force: true });
      console.error(`${arxivId}: wrote public/previews/${arxivId}.jpg`);
    } catch (error) {
      failures += 1;
      console.error(`${arxivId || "missing"}: ${error instanceof Error ? error.message : "preview failed"}`);
    }
  }
} finally {
  writePreviewManifest();
  rmSync(workDir, { recursive: true, force: true });
}

if (failures) process.exitCode = 1;
